---
- fail: msg="jupyterhub_admin_user is not defined"
  when: jupyterhub_admin_user == ''

- include: jupyterhub.yml
- include: stats.yml
- include: cull.yml

- name: install docker compose
  template: src=docker-compose.yml dest=/home/centos/docker-compose.yml

- name: stop docker containers
  command: /usr/local/bin/docker-compose stop

- name: remove docker containers
  command: /usr/local/bin/docker-compose rm -f

- name: pull docker images
  command: /usr/local/bin/docker-compose pull

- name: build docker images
  command: /usr/local/bin/docker-compose build

- name: run jupyterhub
  command: /usr/local/bin/docker-compose up -d jupyterhub

- name: wait for jupyterhub to start
  command: docker logs centos_jupyterhub_1
  register: jpy_status
  until: jpy_status.stderr.find("JupyterHub is now running") != -1
  retries: 5
  delay: 5

- name: get a jupyterhub api token
  command: docker exec centos_jupyterhub_1 jupyterhub token -f /srv/jupyterhub_config/jupyterhub_config.py {{ jupyterhub_admin_user }}
  register: jpy_api_token

- name: start remaining services
  shell: JPY_API_TOKEN={{ jpy_api_token.stdout }} JUPYTERHUB_API_TOKEN={{ jpy_api_token.stdout }} /usr/local/bin/docker-compose up -d --no-recreate
