httpd:
  build: /srv/httpd
  restart: always
  ports:
    - 80:80
    - 443:443
  volumes:
    - /home/centos/.docker:/root/.docker
    - "{{ site_key_path }}:{{ site_key_path }}:ro"
    - "{{ site_cert_path }}:{{ site_cert_path }}:ro"
