---
- name: create /srv/cron directory
  file: path=/srv/cron state=directory
  tags:
  - cron

- name: copy crontab
  template: src=crontab.j2 dest=/srv/cron/crontab
  tags:
  - cron

- name: copy student list
  template: src=studentlist.j2 dest=/srv/cron/studentlist
  tags:
  - cron

- name: copy Dockerfile for jupyterhub
  copy: src=Dockerfile dest=/srv/cron/Dockerfile
  tags:
  - cron

- name: stop and remove cron container
  shell: docker ps -a | grep centos_cron_1 > /dev/null && docker rm -f centos_cron_1 || true
  tags:
  - cron

- name: bulid cron image
  command: docker build -t cron /srv/cron
  tags:
  - cron

- name: run cron container
  command: docker run -d --name centos_cron_1 -v /mnt/volume:/mnt/volume cron
  tags:
  - cron
