FROM lcdm/accy

USER root

ADD nbgrader_config.py /opt/conda/etc/jupyter/nbgrader_config.py

CMD ["start-singleuser.sh"]

USER $NB_USER
ENV TZ America/Chicago

ENV PYTHONPATH /home/$NB_USER/.accy/rubric:$PYTHONPATH

# NLTK was installed with something like
# $ sudo docker run --rm -it -v /mnt/volume/shared/accy571/readonly/data:/mnt/data python:3 bash
# # pip install nltk
# # python -m nltk.downloader -d /mnt/data/nltk_data all
ENV NLTK_DATA /home/$NB_USER/accy571/readonly/data/nltk_data
