---
- name: install nfs pakcages
  yum: name=nfs-utils,libnfsidmap state=latest

- name: mount EFS
  mount: name=/mnt/volume src={{ aws_efs_dns }}:/ fstype=nfs4 opts=nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 state=mounted
